import { Component, OnInit } from '@angular/core';
import * as pdfMake from 'pdfmake/build/pdfmake';
import * as pdfFonts from 'pdfmake/build/vfs_fonts';
(pdfMake as any).vfs = pdfFonts.pdfMake.vfs
@Component({
  selector: 'app-test-model',
  templateUrl: './test-model.component.html',
  styleUrls: ['./test-model.component.css']
})
export class TestModelComponent {
  generateAndDownloadPDF() {
    // Define your invoice content here
    test:String 
    const header = [
      {
          text: 'Description equipament',

          // bold: true,
          // fontFamily: 'Roboto',
          // decoration: 'underline',

          // margin: [0, 20, 0, 0],
          // alignment: 'center',

          // image: 'data:image/jpeg;base64,/9j/END_DATAURL_BASE64'

      }
  ];

    let documentDefinition = {
      header: [header],
      content: [
        { text: 'Invoice', style: 'header' },
        { text: 'Generated by pdfmake in Angular', style: 'subheader' },
        { text: 'Invoice Details', style: 'subheader' },
        {
          table: {
            headerRows: 1,
            widths: ['*', 'auto', 'auto', 'auto'],
            body: [
              ['Item', 'Description', 'Quantity', 'Price'],
              ['Item 1', 'Description 1', 1, 100],
              ['Item 2', 'Description 2', 2, 50],
            ],
          },
        },
        { text: 'Thank you for your business!', style: 'subheader' },
      ]
    };
    
    // Create the PDF
    pdfMake.createPdf(documentDefinition).open();

    // Download the PDF
    // pdfDocGenerator.download('invoice.pdf');
  }
}
